"""add collection points for bulk tracking

Revision ID: 02da5aa05a35
Revises: b9958abfd70b
Create Date: 2026-03-22 16:54:34.120690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.core.db_types

# revision identifiers, used by Alembic.
revision: str = '02da5aa05a35'
down_revision: Union[str, None] = 'b9958abfd70b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_points',
    sa.Column('id', app.core.db_types.UUID(), nullable=False),
    sa.Column('collection_id', app.core.db_types.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('account_no', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'account_no', name='uq_collection_point_account'),
    schema='ingestion'
    )
    op.create_index(op.f('ix_ingestion_collection_points_account_no'), 'collection_points', ['account_no'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_collection_points_collection_id'), 'collection_points', ['collection_id'], unique=False, schema='ingestion')
    op.add_column('transactions', sa.Column('collection_point_id', app.core.db_types.UUID(), nullable=True), schema='ingestion')
    op.create_index('idx_transactions_collection_point', 'transactions', ['collection_id', 'collection_point_id'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_transactions_collection_point_id'), 'transactions', ['collection_point_id'], unique=False, schema='ingestion')
    op.create_foreign_key(None, 'transactions', 'collection_points', ['collection_point_id'], ['id'], source_schema='ingestion', referent_schema='ingestion', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', schema='ingestion', type_='foreignkey')
    op.drop_index(op.f('ix_ingestion_transactions_collection_point_id'), table_name='transactions', schema='ingestion')
    op.drop_index('idx_transactions_collection_point', table_name='transactions', schema='ingestion')
    op.drop_column('transactions', 'collection_point_id', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_collection_points_collection_id'), table_name='collection_points', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_collection_points_account_no'), table_name='collection_points', schema='ingestion')
    op.drop_table('collection_points', schema='ingestion')
    # ### end Alembic commands ###