"""psp and ingestion setup

Revision ID: 0d96f4e2d5c4
Revises: a2ab9c6c02c3
Create Date: 2026-03-20 21:24:50.801858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from app.core.db_types import UUID as PesaUUID

# revision identifiers, used by Alembic.
revision: str = '0d96f4e2d5c4'
down_revision: Union[str, None] = 'a2ab9c6c02c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psp_configs',
    sa.Column('id', PesaUUID(), nullable=False),
    sa.Column('collection_id', PesaUUID(), nullable=False),
    sa.Column('psp_type', sa.Enum('MPESA', 'KCB', 'EQUITY', 'COOP', 'INTASEND', 'SMARTPAY', 'SWIFT', 'CUSTOM', name='psptype'), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('paybill', sa.Text(), nullable=True),
    sa.Column('webhook_url', sa.Text(), nullable=False),
    sa.Column('credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', PesaUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='accounts'
    )
    op.create_index('idx_psp_configs_collection_active', 'psp_configs', ['collection_id', 'is_active'], unique=False, schema='accounts')
    op.create_index('idx_psp_configs_collection_type', 'psp_configs', ['collection_id', 'psp_type'], unique=False, schema='accounts')
    op.create_index(op.f('ix_accounts_psp_configs_collection_id'), 'psp_configs', ['collection_id'], unique=False, schema='accounts')
    op.create_index(op.f('ix_accounts_psp_configs_is_active'), 'psp_configs', ['is_active'], unique=False, schema='accounts')
    op.create_index(op.f('ix_accounts_psp_configs_psp_type'), 'psp_configs', ['psp_type'], unique=False, schema='accounts')
    op.create_table('transactions',
    sa.Column('id', PesaUUID(), nullable=False),
    sa.Column('collection_id', PesaUUID(), nullable=False),
    sa.Column('psp_config_id', PesaUUID(), nullable=True),
    sa.Column('psp_type', sa.Text(), nullable=False),
    sa.Column('psp_ref', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('account_no', sa.Text(), nullable=True),
    sa.Column('payer_name', sa.Text(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('RAW', 'UNMATCHED', 'MATCHED', 'DUPLICATE', 'MANUAL', name='transactionstatus'), nullable=False),
    sa.Column('matched_obligation_id', PesaUUID(), nullable=True),
    sa.Column('matched_at', sa.DateTime(), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['matched_obligation_id'], ['obligations.obligations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['psp_config_id'], ['accounts.psp_configs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'psp_ref', name='uq_transaction_collection_psp_ref'),
    schema='ingestion'
    )
    op.create_index('idx_transactions_collection_account', 'transactions', ['collection_id', 'account_no'], unique=False, schema='ingestion')
    op.create_index('idx_transactions_collection_ingested', 'transactions', ['collection_id', 'ingested_at'], unique=False, schema='ingestion')
    op.create_index('idx_transactions_collection_status', 'transactions', ['collection_id', 'status'], unique=False, schema='ingestion')
    op.create_index('idx_transactions_psp_type_status', 'transactions', ['psp_type', 'status'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_transactions_account_no'), 'transactions', ['account_no'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_transactions_collection_id'), 'transactions', ['collection_id'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_transactions_ingested_at'), 'transactions', ['ingested_at'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_transactions_matched_obligation_id'), 'transactions', ['matched_obligation_id'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_transactions_phone'), 'transactions', ['phone'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_transactions_psp_config_id'), 'transactions', ['psp_config_id'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_transactions_psp_ref'), 'transactions', ['psp_ref'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_transactions_psp_type'), 'transactions', ['psp_type'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_transactions_status'), 'transactions', ['status'], unique=False, schema='ingestion')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingestion_transactions_status'), table_name='transactions', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_transactions_psp_type'), table_name='transactions', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_transactions_psp_ref'), table_name='transactions', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_transactions_psp_config_id'), table_name='transactions', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_transactions_phone'), table_name='transactions', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_transactions_matched_obligation_id'), table_name='transactions', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_transactions_ingested_at'), table_name='transactions', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_transactions_collection_id'), table_name='transactions', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_transactions_account_no'), table_name='transactions', schema='ingestion')
    op.drop_index('idx_transactions_psp_type_status', table_name='transactions', schema='ingestion')
    op.drop_index('idx_transactions_collection_status', table_name='transactions', schema='ingestion')
    op.drop_index('idx_transactions_collection_ingested', table_name='transactions', schema='ingestion')
    op.drop_index('idx_transactions_collection_account', table_name='transactions', schema='ingestion')
    op.drop_table('transactions', schema='ingestion')
    op.drop_index(op.f('ix_accounts_psp_configs_psp_type'), table_name='psp_configs', schema='accounts')
    op.drop_index(op.f('ix_accounts_psp_configs_is_active'), table_name='psp_configs', schema='accounts')
    op.drop_index(op.f('ix_accounts_psp_configs_collection_id'), table_name='psp_configs', schema='accounts')
    op.drop_index('idx_psp_configs_collection_type', table_name='psp_configs', schema='accounts')
    op.drop_index('idx_psp_configs_collection_active', table_name='psp_configs', schema='accounts')
    op.drop_table('psp_configs', schema='accounts')
    # ### end Alembic commands ###