"""Add goal_period to CollectionPoint

Revision ID: 2220d86d2c39
Revises: 6c40c80cb4d5
Create Date: 2026-04-07 11:05:11.586083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2220d86d2c39'
down_revision: Union[str, None] = '6c40c80cb4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Needs to be created before use
    op.execute("CREATE TYPE collectiongoalperiod AS ENUM ('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', 'CUSTOM');")
    op.add_column('collection_points', sa.Column('goal_period', postgresql.ENUM('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', 'CUSTOM', name='collectiongoalperiod', create_type=False), server_default='CUSTOM', nullable=False), schema='ingestion')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection_points', 'goal_period', schema='ingestion')
    op.execute("DROP TYPE collectiongoalperiod;")
    # ### end Alembic commands ###