"""business profile and notification logs

Revision ID: 45f68a2df8c6
Revises: 0d96f4e2d5c4
Create Date: 2026-03-20 21:59:44.741772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from app.core.db_types import UUID as PesaUUID 

# revision identifiers, used by Alembic.
revision: str = '45f68a2df8c6'
down_revision: Union[str, None] = '0d96f4e2d5c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_profiles',
    sa.Column('id', PesaUUID(), nullable=False),
    sa.Column('collection_id', PesaUUID(), nullable=False),
    sa.Column('business_name', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('email_from', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', PesaUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='accounts'
    )
    op.create_index(op.f('ix_accounts_business_profiles_collection_id'), 'business_profiles', ['collection_id'], unique=True, schema='accounts')
    op.create_table('notification_logs',
    sa.Column('id', PesaUUID(), nullable=False),
    sa.Column('collection_id', PesaUUID(), nullable=False),
    sa.Column('payer_id', PesaUUID(), nullable=True),
    sa.Column('channel', sa.Enum('SMS', 'EMAIL', 'WHATSAPP', name='notifchannel'), nullable=False),
    sa.Column('recipient', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('template_id', PesaUUID(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'SENT', 'FAILED', 'SKIPPED', name='notifstatus'), nullable=False),
    sa.Column('provider_ref', sa.Text(), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='notifications'
    )
    op.create_index('idx_notif_logs_collection_channel', 'notification_logs', ['collection_id', 'channel'], unique=False, schema='notifications')
    op.create_index('idx_notif_logs_collection_event', 'notification_logs', ['collection_id', 'event_type'], unique=False, schema='notifications')
    op.create_index('idx_notif_logs_collection_status', 'notification_logs', ['collection_id', 'status'], unique=False, schema='notifications')
    op.create_index(op.f('ix_notifications_notification_logs_channel'), 'notification_logs', ['channel'], unique=False, schema='notifications')
    op.create_index(op.f('ix_notifications_notification_logs_collection_id'), 'notification_logs', ['collection_id'], unique=False, schema='notifications')
    op.create_index(op.f('ix_notifications_notification_logs_event_type'), 'notification_logs', ['event_type'], unique=False, schema='notifications')
    op.create_index(op.f('ix_notifications_notification_logs_payer_id'), 'notification_logs', ['payer_id'], unique=False, schema='notifications')
    op.create_index(op.f('ix_notifications_notification_logs_status'), 'notification_logs', ['status'], unique=False, schema='notifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_notification_logs_status'), table_name='notification_logs', schema='notifications')
    op.drop_index(op.f('ix_notifications_notification_logs_payer_id'), table_name='notification_logs', schema='notifications')
    op.drop_index(op.f('ix_notifications_notification_logs_event_type'), table_name='notification_logs', schema='notifications')
    op.drop_index(op.f('ix_notifications_notification_logs_collection_id'), table_name='notification_logs', schema='notifications')
    op.drop_index(op.f('ix_notifications_notification_logs_channel'), table_name='notification_logs', schema='notifications')
    op.drop_index('idx_notif_logs_collection_status', table_name='notification_logs', schema='notifications')
    op.drop_index('idx_notif_logs_collection_event', table_name='notification_logs', schema='notifications')
    op.drop_index('idx_notif_logs_collection_channel', table_name='notification_logs', schema='notifications')
    op.drop_table('notification_logs', schema='notifications')
    op.drop_index(op.f('ix_accounts_business_profiles_collection_id'), table_name='business_profiles', schema='accounts')
    op.drop_table('business_profiles', schema='accounts')
    # ### end Alembic commands ###