"""expand billing with invoice and cp fees

Revision ID: 6699952c7583
Revises: a1b2c3d4e5f6
Create Date: 2026-04-08 16:20:47.234901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6699952c7583'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Manually handle the Enum expansion for 'wallettxevent'
    # PostgreSQL requires a separate transaction or specific handling to add values to enums.
    # But since we are in a migration, we can use op.execute.
    op.execute("COMMIT") # End transaction for ADD VALUE
    op.execute("ALTER TYPE billing.wallettxevent ADD VALUE IF NOT EXISTS 'invoice'")

    op.add_column('platform_invoices', sa.Column('invoice_count', sa.Integer(), nullable=False, server_default='0'), schema='billing')
    op.add_column('platform_invoices', sa.Column('invoice_fee_total_kes', sa.Numeric(precision=12, scale=4), nullable=False, server_default='0'), schema='billing')
    op.add_column('platform_invoices', sa.Column('collection_point_count', sa.Integer(), nullable=False, server_default='0'), schema='billing')
    op.add_column('platform_invoices', sa.Column('collection_point_fee_total_kes', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'), schema='billing')
    
    # Remove the server_defaults after creation if we don't want them permanent
    op.alter_column('platform_invoices', 'invoice_count', server_default=None, schema='billing')
    op.alter_column('platform_invoices', 'invoice_fee_total_kes', server_default=None, schema='billing')
    op.alter_column('platform_invoices', 'collection_point_count', server_default=None, schema='billing')
    op.alter_column('platform_invoices', 'collection_point_fee_total_kes', server_default=None, schema='billing')

    op.add_column('subscription_plans', sa.Column('invoice_fee_kes', sa.Numeric(precision=10, scale=4), nullable=False, server_default='0'), schema='billing')
    op.add_column('subscription_plans', sa.Column('collection_point_fee_kes', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'), schema='billing')
    op.alter_column('subscription_plans', 'invoice_fee_kes', server_default=None, schema='billing')
    op.alter_column('subscription_plans', 'collection_point_fee_kes', server_default=None, schema='billing')

    op.add_column('tenant_subscriptions', sa.Column('invoice_count', sa.Integer(), nullable=False, server_default='0'), schema='billing')
    op.alter_column('tenant_subscriptions', 'invoice_count', server_default=None, schema='billing')

    # Fix indices and constraints
    op.drop_constraint('platform_invoices_invoice_number_key', 'platform_invoices', schema='billing', type_='unique')
    op.create_index(op.f('ix_billing_platform_invoices_collection_id'), 'platform_invoices', ['collection_id'], unique=False, schema='billing')
    op.create_index(op.f('ix_billing_platform_invoices_invoice_number'), 'platform_invoices', ['invoice_number'], unique=True, schema='billing')
    op.create_index(op.f('ix_billing_platform_invoices_status'), 'platform_invoices', ['status'], unique=False, schema='billing')
    
    op.drop_constraint('subscription_plans_slug_key', 'subscription_plans', schema='billing', type_='unique')
    op.create_index(op.f('ix_billing_subscription_plans_slug'), 'subscription_plans', ['slug'], unique=True, schema='billing')
    
    op.drop_constraint('tenant_subscriptions_collection_id_key', 'tenant_subscriptions', schema='billing', type_='unique')
    op.create_index(op.f('ix_billing_tenant_subscriptions_collection_id'), 'tenant_subscriptions', ['collection_id'], unique=True, schema='billing')
    op.create_index(op.f('ix_billing_tenant_subscriptions_plan_id'), 'tenant_subscriptions', ['plan_id'], unique=False, schema='billing')
    op.create_index(op.f('ix_billing_tenant_subscriptions_status'), 'tenant_subscriptions', ['status'], unique=False, schema='billing')
    
    op.drop_constraint('tenant_wallets_collection_id_key', 'tenant_wallets', schema='billing', type_='unique')
    op.create_index(op.f('ix_billing_tenant_wallets_collection_id'), 'tenant_wallets', ['collection_id'], unique=True, schema='billing')
    
    op.create_index(op.f('ix_billing_wallet_transactions_collection_id'), 'wallet_transactions', ['collection_id'], unique=False, schema='billing')
    op.create_index(op.f('ix_billing_wallet_transactions_event_type'), 'wallet_transactions', ['event_type'], unique=False, schema='billing')
    op.create_index(op.f('ix_billing_wallet_transactions_reference'), 'wallet_transactions', ['reference'], unique=False, schema='billing')
    op.create_index(op.f('ix_billing_wallet_transactions_tx_type'), 'wallet_transactions', ['tx_type'], unique=False, schema='billing')
    op.create_index(op.f('ix_billing_wallet_transactions_wallet_id'), 'wallet_transactions', ['wallet_id'], unique=False, schema='billing')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_billing_wallet_transactions_wallet_id'), table_name='wallet_transactions', schema='billing')
    op.drop_index(op.f('ix_billing_wallet_transactions_tx_type'), table_name='wallet_transactions', schema='billing')
    op.drop_index(op.f('ix_billing_wallet_transactions_reference'), table_name='wallet_transactions', schema='billing')
    op.drop_index(op.f('ix_billing_wallet_transactions_event_type'), table_name='wallet_transactions', schema='billing')
    op.drop_index(op.f('ix_billing_wallet_transactions_collection_id'), table_name='wallet_transactions', schema='billing')
    op.alter_column('wallet_transactions', 'event_type',
               existing_type=sa.Enum('reconciliation', 'sms', 'email', 'invoice', 'subscription_fee', 'topup', 'reversal', name='wallettxevent'),
               type_=postgresql.ENUM('reconciliation', 'sms', 'email', 'subscription_fee', 'topup', 'reversal', name='wallettxevent', schema='billing'),
               existing_nullable=False,
               schema='billing')
    op.alter_column('wallet_transactions', 'tx_type',
               existing_type=sa.Enum('topup', 'deduction', 'reversal', 'subscription', name='wallettxtype'),
               type_=postgresql.ENUM('topup', 'deduction', 'reversal', 'subscription', name='wallettxtype', schema='billing'),
               existing_nullable=False,
               schema='billing')
    op.drop_index(op.f('ix_billing_tenant_wallets_collection_id'), table_name='tenant_wallets', schema='billing')
    op.create_unique_constraint('tenant_wallets_collection_id_key', 'tenant_wallets', ['collection_id'], schema='billing')
    op.drop_index(op.f('ix_billing_tenant_subscriptions_status'), table_name='tenant_subscriptions', schema='billing')
    op.drop_index(op.f('ix_billing_tenant_subscriptions_plan_id'), table_name='tenant_subscriptions', schema='billing')
    op.drop_index(op.f('ix_billing_tenant_subscriptions_collection_id'), table_name='tenant_subscriptions', schema='billing')
    op.create_unique_constraint('tenant_subscriptions_collection_id_key', 'tenant_subscriptions', ['collection_id'], schema='billing')
    op.alter_column('tenant_subscriptions', 'status',
               existing_type=sa.Enum('trial', 'active', 'suspended', 'blocked', 'cancelled', name='subscriptionstatus'),
               type_=postgresql.ENUM('trial', 'active', 'suspended', 'blocked', 'cancelled', name='subscriptionstatus', schema='billing'),
               existing_nullable=False,
               schema='billing')
    op.drop_column('tenant_subscriptions', 'invoice_count', schema='billing')
    op.drop_index(op.f('ix_billing_subscription_plans_slug'), table_name='subscription_plans', schema='billing')
    op.create_unique_constraint('subscription_plans_slug_key', 'subscription_plans', ['slug'], schema='billing')
    op.alter_column('subscription_plans', 'slug',
               existing_type=sa.Enum('starter', 'growth', 'enterprise', name='planslug'),
               type_=postgresql.ENUM('starter', 'growth', 'enterprise', name='planslug', schema='billing'),
               existing_nullable=False,
               schema='billing')
    op.drop_column('subscription_plans', 'collection_point_fee_kes', schema='billing')
    op.drop_column('subscription_plans', 'invoice_fee_kes', schema='billing')
    op.drop_index(op.f('ix_billing_platform_invoices_status'), table_name='platform_invoices', schema='billing')
    op.drop_index(op.f('ix_billing_platform_invoices_invoice_number'), table_name='platform_invoices', schema='billing')
    op.drop_index(op.f('ix_billing_platform_invoices_collection_id'), table_name='platform_invoices', schema='billing')
    op.create_unique_constraint('platform_invoices_invoice_number_key', 'platform_invoices', ['invoice_number'], schema='billing')
    op.alter_column('platform_invoices', 'status',
               existing_type=sa.Enum('draft', 'sent', 'paid', 'overdue', 'void', name='invoicestatus'),
               type_=postgresql.ENUM('draft', 'sent', 'paid', 'overdue', 'void', name='invoicestatus', schema='billing'),
               existing_nullable=False,
               schema='billing')
    op.drop_column('platform_invoices', 'collection_point_fee_total_kes', schema='billing')
    op.drop_column('platform_invoices', 'collection_point_count', schema='billing')
    op.drop_column('platform_invoices', 'invoice_fee_total_kes', schema='billing')
    op.drop_column('platform_invoices', 'invoice_count', schema='billing')
    # ### end Alembic commands ###