"""Evolve CollectionPoint to financial instrument

Revision ID: 6c40c80cb4d5
Revises: c3a7f1b2e4d9
Create Date: 2026-04-07 10:41:30.991987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.core.db_types


# revision identifiers, used by Alembic.
revision: str = '6c40c80cb4d5'
down_revision: Union[str, None] = 'c3a7f1b2e4d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_point_psps',
    sa.Column('id', app.core.db_types.UUID(), nullable=False),
    sa.Column('collection_point_id', app.core.db_types.UUID(), nullable=False),
    sa.Column('psp_config_id', app.core.db_types.UUID(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_point_id'], ['ingestion.collection_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['psp_config_id'], ['accounts.psp_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_point_id', 'psp_config_id', name='uq_cp_psp'),
    schema='ingestion'
    )
    op.create_index(op.f('ix_ingestion_collection_point_psps_collection_point_id'), 'collection_point_psps', ['collection_point_id'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_collection_point_psps_psp_config_id'), 'collection_point_psps', ['psp_config_id'], unique=False, schema='ingestion')
    
    # Needs to be created before use
    op.execute("CREATE TYPE collectionpointtype AS ENUM ('CAMPAIGN', 'FLEET', 'DONATION', 'BRANCH', 'EVENT', 'CUSTOM');")
    
    op.add_column('collection_points', sa.Column('cp_type', postgresql.ENUM('CAMPAIGN', 'FLEET', 'DONATION', 'BRANCH', 'EVENT', 'CUSTOM', name='collectionpointtype', create_type=False), nullable=True), schema='ingestion')
    op.execute("UPDATE ingestion.collection_points SET cp_type = 'CUSTOM'")
    op.alter_column('collection_points', 'cp_type', nullable=False, schema='ingestion')
    
    op.add_column('collection_points', sa.Column('goal_amount', sa.Numeric(precision=18, scale=2), nullable=True), schema='ingestion')
    op.add_column('collection_points', sa.Column('currency', sa.String(length=3), nullable=False, server_default='KES'), schema='ingestion')
    op.add_column('collection_points', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True), schema='ingestion')
    op.add_column('collection_points', sa.Column('end_date', sa.DateTime(timezone=True), nullable=True), schema='ingestion')
    op.add_column('collection_points', sa.Column('compliance_threshold', sa.Numeric(precision=18, scale=2), nullable=True), schema='ingestion')
    op.add_column('collection_points', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')), schema='ingestion')
    
    op.create_index('idx_cp_collection_active', 'collection_points', ['collection_id', 'is_active'], unique=False, schema='ingestion')
    op.create_index('idx_cp_collection_type', 'collection_points', ['collection_id', 'cp_type'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_collection_points_cp_type'), 'collection_points', ['cp_type'], unique=False, schema='ingestion')
    op.create_index('idx_transactions_collection_date_amount', 'transactions', ['collection_id', 'ingested_at', 'amount'], unique=False, schema='ingestion')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_transactions_collection_date_amount', table_name='transactions', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_collection_points_cp_type'), table_name='collection_points', schema='ingestion')
    op.drop_index('idx_cp_collection_type', table_name='collection_points', schema='ingestion')
    op.drop_index('idx_cp_collection_active', table_name='collection_points', schema='ingestion')
    
    op.drop_column('collection_points', 'updated_at', schema='ingestion')
    op.drop_column('collection_points', 'compliance_threshold', schema='ingestion')
    op.drop_column('collection_points', 'end_date', schema='ingestion')
    op.drop_column('collection_points', 'start_date', schema='ingestion')
    op.drop_column('collection_points', 'currency', schema='ingestion')
    op.drop_column('collection_points', 'goal_amount', schema='ingestion')
    op.drop_column('collection_points', 'cp_type', schema='ingestion')
    op.execute("DROP TYPE collectionpointtype;")
    
    op.drop_index(op.f('ix_ingestion_collection_point_psps_psp_config_id'), table_name='collection_point_psps', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_collection_point_psps_collection_point_id'), table_name='collection_point_psps', schema='ingestion')
    op.drop_table('collection_point_psps', schema='ingestion')
    # ### end Alembic commands ###