"""obligation setup

Revision ID: a2ab9c6c02c3
Revises: ac1309b9e1fd
Create Date: 2026-03-20 21:08:09.879675

"""
from typing import Sequence, Union

from alembic import op
import app.core.db_types
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2ab9c6c02c3'
down_revision: Union[str, None] = 'ac1309b9e1fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_templates',
    sa.Column('id', app.core.db_types.UUID(), nullable=False),
    sa.Column('collection_id', app.core.db_types.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('template_type', sa.Enum('PAYMENT_REMINDER', 'OVERDUE_NOTICE', 'PAYMENT_RECEIPT', 'STATEMENT', 'CUSTOM', name='templatetype'), nullable=False),
    sa.Column('channel', sa.Enum('SMS', 'WHATSAPP', 'EMAIL', name='templatechannel'), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_by', app.core.db_types.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='obligations'
    )
    op.create_index('idx_notif_templates_collection_channel', 'notification_templates', ['collection_id', 'channel'], unique=False, schema='obligations')
    op.create_index('idx_notif_templates_collection_type', 'notification_templates', ['collection_id', 'template_type'], unique=False, schema='obligations')
    op.create_index(op.f('ix_obligations_notification_templates_channel'), 'notification_templates', ['channel'], unique=False, schema='obligations')
    op.create_index(op.f('ix_obligations_notification_templates_collection_id'), 'notification_templates', ['collection_id'], unique=False, schema='obligations')
    op.create_index(op.f('ix_obligations_notification_templates_template_type'), 'notification_templates', ['template_type'], unique=False, schema='obligations')
    op.create_table('payer_groups',
    sa.Column('id', app.core.db_types.UUID(), nullable=False),
    sa.Column('collection_id', app.core.db_types.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('group_type', sa.Enum('APARTMENT_BLOCK', 'UNIT', 'SCHOOL_CLASS', 'BUS_ROUTE', 'INVOICE_GROUP', 'CHAMA_GROUP', 'UTILITY_ZONE', 'CUSTOM', name='grouptype'), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', app.core.db_types.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='obligations'
    )
    op.create_index('idx_payer_groups_collection_type', 'payer_groups', ['collection_id', 'group_type'], unique=False, schema='obligations')
    op.create_index(op.f('ix_obligations_payer_groups_collection_id'), 'payer_groups', ['collection_id'], unique=False, schema='obligations')
    op.create_index(op.f('ix_obligations_payer_groups_group_type'), 'payer_groups', ['group_type'], unique=False, schema='obligations')
    op.create_table('payers',
    sa.Column('id', app.core.db_types.UUID(), nullable=False),
    sa.Column('collection_id', app.core.db_types.UUID(), nullable=False),
    sa.Column('group_id', app.core.db_types.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('account_no', sa.Text(), nullable=True),
    sa.Column('identifier', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', app.core.db_types.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['obligations.payer_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='obligations'
    )
    op.create_index('idx_payers_account_no', 'payers', ['collection_id', 'account_no'], unique=False, schema='obligations')
    op.create_index('idx_payers_collection_active', 'payers', ['collection_id', 'is_active'], unique=False, schema='obligations')
    op.create_index('idx_payers_collection_group', 'payers', ['collection_id', 'group_id'], unique=False, schema='obligations')
    op.create_index(op.f('ix_obligations_payers_account_no'), 'payers', ['account_no'], unique=False, schema='obligations')
    op.create_index(op.f('ix_obligations_payers_collection_id'), 'payers', ['collection_id'], unique=False, schema='obligations')
    op.create_index(op.f('ix_obligations_payers_group_id'), 'payers', ['group_id'], unique=False, schema='obligations')
    op.create_index(op.f('ix_obligations_payers_is_active'), 'payers', ['is_active'], unique=False, schema='obligations')
    op.create_index(op.f('ix_obligations_payers_phone'), 'payers', ['phone'], unique=False, schema='obligations')
    op.create_table('obligations',
    sa.Column('id', app.core.db_types.UUID(), nullable=False),
    sa.Column('collection_id', app.core.db_types.UUID(), nullable=False),
    sa.Column('payer_id', app.core.db_types.UUID(), nullable=False),
    sa.Column('account_no', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount_due', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PARTIAL', 'PAID', 'OVERDUE', 'CANCELLED', name='obligationstatus'), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', app.core.db_types.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payer_id'], ['obligations.payers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='obligations'
    )
    op.create_index('idx_obligations_collection_account', 'obligations', ['collection_id', 'account_no'], unique=False, schema='obligations')
    op.create_index('idx_obligations_collection_due_date', 'obligations', ['collection_id', 'due_date'], unique=False, schema='obligations')
    op.create_index('idx_obligations_collection_status', 'obligations', ['collection_id', 'status'], unique=False, schema='obligations')
    op.create_index('idx_obligations_created_at_desc', 'obligations', ['created_at'], unique=False, schema='obligations', postgresql_using='btree')
    op.create_index('idx_obligations_payer_status', 'obligations', ['payer_id', 'status'], unique=False, schema='obligations')
    op.create_index(op.f('ix_obligations_obligations_account_no'), 'obligations', ['account_no'], unique=False, schema='obligations')
    op.create_index(op.f('ix_obligations_obligations_collection_id'), 'obligations', ['collection_id'], unique=False, schema='obligations')
    op.create_index(op.f('ix_obligations_obligations_created_by'), 'obligations', ['created_by'], unique=False, schema='obligations')
    op.create_index(op.f('ix_obligations_obligations_is_recurring'), 'obligations', ['is_recurring'], unique=False, schema='obligations')
    op.create_index(op.f('ix_obligations_obligations_payer_id'), 'obligations', ['payer_id'], unique=False, schema='obligations')
    op.create_index(op.f('ix_obligations_obligations_status'), 'obligations', ['status'], unique=False, schema='obligations')
    op.create_table('recurring_configs',
    sa.Column('id', app.core.db_types.UUID(), nullable=False),
    sa.Column('obligation_id', app.core.db_types.UUID(), nullable=False),
    sa.Column('recurrence_type', sa.Enum('MONTHLY', 'WEEKLY', 'TERM', 'CUSTOM', name='recurrencetype'), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('next_due_date', sa.DateTime(), nullable=True),
    sa.Column('grace_period_days', sa.Integer(), nullable=False),
    sa.Column('auto_generate', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.obligations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='obligations'
    )
    op.create_index('idx_recurring_next_due', 'recurring_configs', ['next_due_date'], unique=False, schema='obligations')
    op.create_index(op.f('ix_obligations_recurring_configs_next_due_date'), 'recurring_configs', ['next_due_date'], unique=False, schema='obligations')
    op.create_index(op.f('ix_obligations_recurring_configs_obligation_id'), 'recurring_configs', ['obligation_id'], unique=True, schema='obligations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_obligations_recurring_configs_obligation_id'), table_name='recurring_configs', schema='obligations')
    op.drop_index(op.f('ix_obligations_recurring_configs_next_due_date'), table_name='recurring_configs', schema='obligations')
    op.drop_index('idx_recurring_next_due', table_name='recurring_configs', schema='obligations')
    op.drop_table('recurring_configs', schema='obligations')
    op.drop_index(op.f('ix_obligations_obligations_status'), table_name='obligations', schema='obligations')
    op.drop_index(op.f('ix_obligations_obligations_payer_id'), table_name='obligations', schema='obligations')
    op.drop_index(op.f('ix_obligations_obligations_is_recurring'), table_name='obligations', schema='obligations')
    op.drop_index(op.f('ix_obligations_obligations_created_by'), table_name='obligations', schema='obligations')
    op.drop_index(op.f('ix_obligations_obligations_collection_id'), table_name='obligations', schema='obligations')
    op.drop_index(op.f('ix_obligations_obligations_account_no'), table_name='obligations', schema='obligations')
    op.drop_index('idx_obligations_payer_status', table_name='obligations', schema='obligations')
    op.drop_index('idx_obligations_created_at_desc', table_name='obligations', schema='obligations', postgresql_using='btree')
    op.drop_index('idx_obligations_collection_status', table_name='obligations', schema='obligations')
    op.drop_index('idx_obligations_collection_due_date', table_name='obligations', schema='obligations')
    op.drop_index('idx_obligations_collection_account', table_name='obligations', schema='obligations')
    op.drop_table('obligations', schema='obligations')
    op.drop_index(op.f('ix_obligations_payers_phone'), table_name='payers', schema='obligations')
    op.drop_index(op.f('ix_obligations_payers_is_active'), table_name='payers', schema='obligations')
    op.drop_index(op.f('ix_obligations_payers_group_id'), table_name='payers', schema='obligations')
    op.drop_index(op.f('ix_obligations_payers_collection_id'), table_name='payers', schema='obligations')
    op.drop_index(op.f('ix_obligations_payers_account_no'), table_name='payers', schema='obligations')
    op.drop_index('idx_payers_collection_group', table_name='payers', schema='obligations')
    op.drop_index('idx_payers_collection_active', table_name='payers', schema='obligations')
    op.drop_index('idx_payers_account_no', table_name='payers', schema='obligations')
    op.drop_table('payers', schema='obligations')
    op.drop_index(op.f('ix_obligations_payer_groups_group_type'), table_name='payer_groups', schema='obligations')
    op.drop_index(op.f('ix_obligations_payer_groups_collection_id'), table_name='payer_groups', schema='obligations')
    op.drop_index('idx_payer_groups_collection_type', table_name='payer_groups', schema='obligations')
    op.drop_table('payer_groups', schema='obligations')
    op.drop_index(op.f('ix_obligations_notification_templates_template_type'), table_name='notification_templates', schema='obligations')
    op.drop_index(op.f('ix_obligations_notification_templates_collection_id'), table_name='notification_templates', schema='obligations')
    op.drop_index(op.f('ix_obligations_notification_templates_channel'), table_name='notification_templates', schema='obligations')
    op.drop_index('idx_notif_templates_collection_type', table_name='notification_templates', schema='obligations')
    op.drop_index('idx_notif_templates_collection_channel', table_name='notification_templates', schema='obligations')
    op.drop_table('notification_templates', schema='obligations')
    # ### end Alembic commands ###