"""first migrate

Revision ID: ac1309b9e1fd
Revises: 
Create Date: 2026-03-19 10:56:23.781148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.db_types


# revision identifiers, used by Alembic.
revision: str = 'ac1309b9e1fd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_log',
    sa.Column('id', app.core.db_types.UUID(), nullable=False),
    sa.Column('event_name', sa.Text(), nullable=False),
    sa.Column('done_by_user_id', app.core.db_types.UUID(), nullable=False),
    sa.Column('to_user_id', app.core.db_types.UUID(), nullable=True),
    sa.Column('event_description', sa.Text(), nullable=True),
    sa.Column('done_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_index('idx_event_log_done_at_desc', 'event_log', ['done_at'], unique=False, schema='auth', postgresql_using='btree')
    op.create_index('idx_event_log_done_by_user_done_at', 'event_log', ['done_by_user_id', 'done_at'], unique=False, schema='auth')
    op.create_index('idx_event_log_event_name_done_at', 'event_log', ['event_name', 'done_at'], unique=False, schema='auth')
    op.create_index('idx_event_log_to_user_done_at', 'event_log', ['to_user_id', 'done_at'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_event_log_done_at'), 'event_log', ['done_at'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_event_log_done_by_user_id'), 'event_log', ['done_by_user_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_event_log_event_name'), 'event_log', ['event_name'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_event_log_to_user_id'), 'event_log', ['to_user_id'], unique=False, schema='auth')
    op.create_table('users',
    sa.Column('id', app.core.db_types.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('auth_type', sa.Enum('EMAIL', 'USERNAME', 'GOOGLE', 'FACEBOOK', 'PHONE', name='authtype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_index('idx_users_auth_type_verified', 'users', ['auth_type', 'verified'], unique=False, schema='auth')
    op.create_index('idx_users_created_at_desc', 'users', ['created_at'], unique=False, schema='auth', postgresql_using='btree')
    op.create_index('idx_users_email_verified', 'users', ['email', 'verified'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_users_auth_type'), 'users', ['auth_type'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_users_created_at'), 'users', ['created_at'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_users_email'), 'users', ['email'], unique=True, schema='auth')
    op.create_index(op.f('ix_auth_users_phone'), 'users', ['phone'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_users_username'), 'users', ['username'], unique=True, schema='auth')
    op.create_index(op.f('ix_auth_users_verified'), 'users', ['verified'], unique=False, schema='auth')
    op.create_table('auth_tokens',
    sa.Column('id', app.core.db_types.UUID(), nullable=False),
    sa.Column('user_id', app.core.db_types.UUID(), nullable=False),
    sa.Column('hash_tokens', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_index('idx_auth_tokens_hash_lookup', 'auth_tokens', ['hash_tokens'], unique=False, schema='auth', postgresql_using='hash')
    op.create_index('idx_auth_tokens_user_sent_at', 'auth_tokens', ['user_id', 'sent_at'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_auth_tokens_hash_tokens'), 'auth_tokens', ['hash_tokens'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_auth_tokens_sent_at'), 'auth_tokens', ['sent_at'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_auth_tokens_user_id'), 'auth_tokens', ['user_id'], unique=False, schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_auth_tokens_user_id'), table_name='auth_tokens', schema='auth')
    op.drop_index(op.f('ix_auth_auth_tokens_sent_at'), table_name='auth_tokens', schema='auth')
    op.drop_index(op.f('ix_auth_auth_tokens_hash_tokens'), table_name='auth_tokens', schema='auth')
    op.drop_index('idx_auth_tokens_user_sent_at', table_name='auth_tokens', schema='auth')
    op.drop_index('idx_auth_tokens_hash_lookup', table_name='auth_tokens', schema='auth', postgresql_using='hash')
    op.drop_table('auth_tokens', schema='auth')
    op.drop_index(op.f('ix_auth_users_verified'), table_name='users', schema='auth')
    op.drop_index(op.f('ix_auth_users_username'), table_name='users', schema='auth')
    op.drop_index(op.f('ix_auth_users_phone'), table_name='users', schema='auth')
    op.drop_index(op.f('ix_auth_users_email'), table_name='users', schema='auth')
    op.drop_index(op.f('ix_auth_users_created_at'), table_name='users', schema='auth')
    op.drop_index(op.f('ix_auth_users_auth_type'), table_name='users', schema='auth')
    op.drop_index('idx_users_email_verified', table_name='users', schema='auth')
    op.drop_index('idx_users_created_at_desc', table_name='users', schema='auth', postgresql_using='btree')
    op.drop_index('idx_users_auth_type_verified', table_name='users', schema='auth')
    op.drop_table('users', schema='auth')
    op.drop_index(op.f('ix_auth_event_log_to_user_id'), table_name='event_log', schema='auth')
    op.drop_index(op.f('ix_auth_event_log_event_name'), table_name='event_log', schema='auth')
    op.drop_index(op.f('ix_auth_event_log_done_by_user_id'), table_name='event_log', schema='auth')
    op.drop_index(op.f('ix_auth_event_log_done_at'), table_name='event_log', schema='auth')
    op.drop_index('idx_event_log_to_user_done_at', table_name='event_log', schema='auth')
    op.drop_index('idx_event_log_event_name_done_at', table_name='event_log', schema='auth')
    op.drop_index('idx_event_log_done_by_user_done_at', table_name='event_log', schema='auth')
    op.drop_index('idx_event_log_done_at_desc', table_name='event_log', schema='auth', postgresql_using='btree')
    op.drop_table('event_log', schema='auth')
    # ### end Alembic commands ###