"""migrate to pg

Revision ID: adcd9070ced1
Revises: 
Create Date: 2026-05-25 15:04:38.189558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.core.db_types

# revision identifiers, used by Alembic.
revision: str = 'adcd9070ced1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_profiles',
    sa.Column('id', app.core.db_types.UUID(), nullable=False),
    sa.Column('collection_id', app.core.db_types.UUID(), nullable=False),
    sa.Column('business_name', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('email_from', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', app.core.db_types.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='accounts'
    )
    op.create_index(op.f('ix_accounts_business_profiles_collection_id'), 'business_profiles', ['collection_id'], unique=True, schema='accounts')
    op.create_table('psp_configs',
    sa.Column('id', app.core.db_types.UUID(), nullable=False),
    sa.Column('collection_id', app.core.db_types.UUID(), nullable=False),
    sa.Column('psp_type', sa.Enum('MPESA', 'KCB', 'EQUITY', 'COOP', 'INTASEND', 'SMARTPAY', 'SWIFT', 'CUSTOM', name='psptype'), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('paybill', sa.Text(), nullable=True),
    sa.Column('webhook_url', sa.Text(), nullable=False),
    sa.Column('credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('till_number', sa.Text(), nullable=True),
    sa.Column('business_key', sa.Text(), nullable=True),
    sa.Column('account_no', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', app.core.db_types.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='accounts'
    )
    op.create_index('idx_psp_configs_collection_active', 'psp_configs', ['collection_id', 'is_active'], unique=False, schema='accounts')
    op.create_index('idx_psp_configs_collection_type', 'psp_configs', ['collection_id', 'psp_type'], unique=False, schema='accounts')
    op.create_index(op.f('ix_accounts_psp_configs_collection_id'), 'psp_configs', ['collection_id'], unique=False, schema='accounts')
    op.create_index(op.f('ix_accounts_psp_configs_is_active'), 'psp_configs', ['is_active'], unique=False, schema='accounts')
    op.create_index(op.f('ix_accounts_psp_configs_psp_type'), 'psp_configs', ['psp_type'], unique=False, schema='accounts')
    op.create_table('event_log',
    sa.Column('id', app.core.db_types.UUID(), nullable=False),
    sa.Column('event_name', sa.Text(), nullable=False),
    sa.Column('done_by_user_id', app.core.db_types.UUID(), nullable=False),
    sa.Column('to_user_id', app.core.db_types.UUID(), nullable=True),
    sa.Column('event_description', sa.Text(), nullable=True),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_index('idx_event_log_done_at_desc', 'event_log', ['done_at'], unique=False, schema='auth', postgresql_using='btree')
    op.create_index('idx_event_log_done_by_user_done_at', 'event_log', ['done_by_user_id', 'done_at'], unique=False, schema='auth')
    op.create_index('idx_event_log_event_name_done_at', 'event_log', ['event_name', 'done_at'], unique=False, schema='auth')
    op.create_index('idx_event_log_to_user_done_at', 'event_log', ['to_user_id', 'done_at'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_event_log_done_at'), 'event_log', ['done_at'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_event_log_done_by_user_id'), 'event_log', ['done_by_user_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_event_log_event_name'), 'event_log', ['event_name'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_event_log_to_user_id'), 'event_log', ['to_user_id'], unique=False, schema='auth')
    op.create_table('users',
    sa.Column('id', app.core.db_types.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('google_id', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('auth_type', sa.Enum('EMAIL', 'USERNAME', 'GOOGLE', 'FACEBOOK', 'PHONE', name='authtype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_index('idx_users_auth_type_verified', 'users', ['auth_type', 'verified'], unique=False, schema='auth')
    op.create_index('idx_users_created_at_desc', 'users', ['created_at'], unique=False, schema='auth', postgresql_using='btree')
    op.create_index('idx_users_email_verified', 'users', ['email', 'verified'], unique=False, schema='auth')
    op.create_index('idx_users_google_id', 'users', ['google_id'], unique=False, schema='auth', postgresql_using='hash')
    op.create_index(op.f('ix_auth_users_auth_type'), 'users', ['auth_type'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_users_created_at'), 'users', ['created_at'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_users_email'), 'users', ['email'], unique=True, schema='auth')
    op.create_index(op.f('ix_auth_users_google_id'), 'users', ['google_id'], unique=True, schema='auth')
    op.create_index(op.f('ix_auth_users_phone'), 'users', ['phone'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_users_username'), 'users', ['username'], unique=True, schema='auth')
    op.create_index(op.f('ix_auth_users_verified'), 'users', ['verified'], unique=False, schema='auth')
    op.create_table('subscription_plans',
    sa.Column('id', app.core.db_types.UUID(), nullable=False),
    sa.Column('slug', sa.Enum('starter', 'growth', 'enterprise', name='planslug'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('monthly_fee_kes', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('recon_fee_kes', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('notification_fee_kes', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('invoice_fee_kes', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('collection_point_fee_kes', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('wallet_minimum_kes', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_branches', sa.Integer(), nullable=False),
    sa.Column('max_psps', sa.Integer(), nullable=False),
    sa.Column('requires_custom_quote', sa.Boolean(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='billing'
    )
    op.create_index(op.f('ix_billing_subscription_plans_slug'), 'subscription_plans', ['slug'], unique=True, schema='billing')
    op.create_table('collection_points',
    sa.Column('id', app.core.db_types.UUID(), nullable=False),
    sa.Column('collection_id', app.core.db_types.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('account_no', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cp_type', sa.Enum('CAMPAIGN', 'FLEET', 'DONATION', 'BRANCH', 'EVENT', 'CUSTOM', name='collectionpointtype'), nullable=False),
    sa.Column('goal_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('goal_period', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', 'CUSTOM', name='collectiongoalperiod'), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('compliance_threshold', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sms_acknowledgement', sa.Boolean(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'account_no', name='uq_collection_point_account'),
    schema='ingestion'
    )
    op.create_index('idx_cp_collection_active', 'collection_points', ['collection_id', 'is_active'], unique=False, schema='ingestion')
    op.create_index('idx_cp_collection_type', 'collection_points', ['collection_id', 'cp_type'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_collection_points_account_no'), 'collection_points', ['account_no'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_collection_points_collection_id'), 'collection_points', ['collection_id'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_collection_points_cp_type'), 'collection_points', ['cp_type'], unique=False, schema='ingestion')
    op.create_table('notification_logs',
    sa.Column('id', app.core.db_types.UUID(), nullable=False),
    sa.Column('collection_id', app.core.db_types.UUID(), nullable=False),
    sa.Column('payer_id', app.core.db_types.UUID(), nullable=True),
    sa.Column('channel', sa.Enum('SMS', 'EMAIL', 'WHATSAPP', name='notifchannel'), nullable=False),
    sa.Column('recipient', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('template_id', app.core.db_types.UUID(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'SENT', 'FAILED', 'SKIPPED', name='notifstatus'), nullable=False),
    sa.Column('provider_ref', sa.Text(), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='notifications'
    )
    op.create_index('idx_notif_logs_collection_channel', 'notification_logs', ['collection_id', 'channel'], unique=False, schema='notifications')
    op.create_index('idx_notif_logs_collection_event', 'notification_logs', ['collection_id', 'event_type'], unique=False, schema='notifications')
    op.create_index('idx_notif_logs_collection_status', 'notification_logs', ['collection_id', 'status'], unique=False, schema='notifications')
    op.create_index(op.f('ix_notifications_notification_logs_channel'), 'notification_logs', ['channel'], unique=False, schema='notifications')
    op.create_index(op.f('ix_notifications_notification_logs_collection_id'), 'notification_logs', ['collection_id'], unique=False, schema='notifications')
    op.create_index(op.f('ix_notifications_notification_logs_event_type'), 'notification_logs', ['event_type'], unique=False, schema='notifications')
    op.create_index(op.f('ix_notifications_notification_logs_payer_id'), 'notification_logs', ['payer_id'], unique=False, schema='notifications')
    op.create_index(op.f('ix_notifications_notification_logs_status'), 'notification_logs', ['status'], unique=False, schema='notifications')
    op.create_table('notification_templates',
    sa.Column('id', app.core.db_types.UUID(), nullable=False),
    sa.Column('collection_id', app.core.db_types.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('template_type', sa.Enum('PAYMENT_REMINDER', 'OVERDUE_NOTICE', 'PAYMENT_RECEIPT', 'PAYMENT_RECEIPT_FULL', 'OBLIGATION_CREATED', 'OBLIGATION_CANCELLED', 'COLLECTION_RECEIPT', 'STATEMENT', 'CUSTOM', name='templatetype'), nullable=False),
    sa.Column('channel', sa.Enum('SMS', 'WHATSAPP', 'EMAIL', 'ALL', name='templatechannel'), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_by', app.core.db_types.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='obligations'
    )
    op.create_index('idx_notif_templates_collection_channel', 'notification_templates', ['collection_id', 'channel'], unique=False, schema='obligations')
    op.create_index('idx_notif_templates_collection_type', 'notification_templates', ['collection_id', 'template_type'], unique=False, schema='obligations')
    op.create_index(op.f('ix_obligations_notification_templates_channel'), 'notification_templates', ['channel'], unique=False, schema='obligations')
    op.create_index(op.f('ix_obligations_notification_templates_collection_id'), 'notification_templates', ['collection_id'], unique=False, schema='obligations')
    op.create_index(op.f('ix_obligations_notification_templates_template_type'), 'notification_templates', ['template_type'], unique=False, schema='obligations')
    op.create_table('payer_groups',
    sa.Column('id', app.core.db_types.UUID(), nullable=False),
    sa.Column('collection_id', app.core.db_types.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('group_type', sa.Enum('APARTMENT_BLOCK', 'UNIT', 'SCHOOL_CLASS', 'BUS_ROUTE', 'INVOICE_GROUP', 'CHAMA_GROUP', 'UTILITY_ZONE', 'CUSTOM', name='grouptype'), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', app.core.db_types.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='obligations'
    )
    op.create_index('idx_payer_groups_collection_type', 'payer_groups', ['collection_id', 'group_type'], unique=False, schema='obligations')
    op.create_index(op.f('ix_obligations_payer_groups_collection_id'), 'payer_groups', ['collection_id'], unique=False, schema='obligations')
    op.create_index(op.f('ix_obligations_payer_groups_group_type'), 'payer_groups', ['group_type'], unique=False, schema='obligations')
    op.create_table('auth_tokens',
    sa.Column('id', app.core.db_types.UUID(), nullable=False),
    sa.Column('user_id', app.core.db_types.UUID(), nullable=False),
    sa.Column('hash_tokens', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_index('idx_auth_tokens_hash_lookup', 'auth_tokens', ['hash_tokens'], unique=False, schema='auth', postgresql_using='hash')
    op.create_index('idx_auth_tokens_user_sent_at', 'auth_tokens', ['user_id', 'sent_at'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_auth_tokens_hash_tokens'), 'auth_tokens', ['hash_tokens'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_auth_tokens_sent_at'), 'auth_tokens', ['sent_at'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_auth_tokens_user_id'), 'auth_tokens', ['user_id'], unique=False, schema='auth')
    op.create_table('platform_invoices',
    sa.Column('id', app.core.db_types.UUID(), nullable=False),
    sa.Column('collection_id', app.core.db_types.UUID(), nullable=False),
    sa.Column('plan_id', app.core.db_types.UUID(), nullable=False),
    sa.Column('invoice_number', sa.Text(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subscription_fee_kes', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('recon_count', sa.Integer(), nullable=False),
    sa.Column('recon_fee_total_kes', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('notification_count', sa.Integer(), nullable=False),
    sa.Column('notification_fee_total_kes', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('invoice_count', sa.Integer(), nullable=False),
    sa.Column('invoice_fee_total_kes', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('collection_point_count', sa.Integer(), nullable=False),
    sa.Column('collection_point_fee_total_kes', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount_kes', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('draft', 'sent', 'paid', 'overdue', 'void', name='invoicestatus'), nullable=False),
    sa.Column('paystack_payment_link', sa.Text(), nullable=True),
    sa.Column('paystack_reference', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['billing.subscription_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'period_start', name='uq_invoice_collection_period'),
    schema='billing'
    )
    op.create_index('idx_platform_invoices_collection', 'platform_invoices', ['collection_id'], unique=False, schema='billing')
    op.create_index('idx_platform_invoices_period', 'platform_invoices', ['period_start', 'period_end'], unique=False, schema='billing')
    op.create_index('idx_platform_invoices_status', 'platform_invoices', ['status'], unique=False, schema='billing')
    op.create_index(op.f('ix_billing_platform_invoices_collection_id'), 'platform_invoices', ['collection_id'], unique=False, schema='billing')
    op.create_index(op.f('ix_billing_platform_invoices_invoice_number'), 'platform_invoices', ['invoice_number'], unique=True, schema='billing')
    op.create_index(op.f('ix_billing_platform_invoices_status'), 'platform_invoices', ['status'], unique=False, schema='billing')
    op.create_table('tenant_subscriptions',
    sa.Column('id', app.core.db_types.UUID(), nullable=False),
    sa.Column('collection_id', app.core.db_types.UUID(), nullable=False),
    sa.Column('plan_id', app.core.db_types.UUID(), nullable=False),
    sa.Column('status', sa.Enum('trial', 'active', 'suspended', 'blocked', 'cancelled', name='subscriptionstatus'), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grace_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recon_count', sa.Integer(), nullable=False),
    sa.Column('notification_count', sa.Integer(), nullable=False),
    sa.Column('invoice_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['billing.subscription_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='billing'
    )
    op.create_index('idx_tenant_subs_collection', 'tenant_subscriptions', ['collection_id'], unique=False, schema='billing')
    op.create_index('idx_tenant_subs_status', 'tenant_subscriptions', ['status'], unique=False, schema='billing')
    op.create_index(op.f('ix_billing_tenant_subscriptions_collection_id'), 'tenant_subscriptions', ['collection_id'], unique=True, schema='billing')
    op.create_index(op.f('ix_billing_tenant_subscriptions_plan_id'), 'tenant_subscriptions', ['plan_id'], unique=False, schema='billing')
    op.create_index(op.f('ix_billing_tenant_subscriptions_status'), 'tenant_subscriptions', ['status'], unique=False, schema='billing')
    op.create_table('collection_point_psps',
    sa.Column('id', app.core.db_types.UUID(), nullable=False),
    sa.Column('collection_point_id', app.core.db_types.UUID(), nullable=False),
    sa.Column('psp_config_id', app.core.db_types.UUID(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_point_id'], ['ingestion.collection_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['psp_config_id'], ['accounts.psp_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_point_id', 'psp_config_id', name='uq_cp_psp'),
    schema='ingestion'
    )
    op.create_index(op.f('ix_ingestion_collection_point_psps_collection_point_id'), 'collection_point_psps', ['collection_point_id'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_collection_point_psps_psp_config_id'), 'collection_point_psps', ['psp_config_id'], unique=False, schema='ingestion')
    op.create_table('payers',
    sa.Column('id', app.core.db_types.UUID(), nullable=False),
    sa.Column('collection_id', app.core.db_types.UUID(), nullable=False),
    sa.Column('group_id', app.core.db_types.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('account_no', sa.Text(), nullable=True),
    sa.Column('identifier', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('credit_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', app.core.db_types.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['obligations.payer_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='obligations'
    )
    op.create_index('idx_payers_account_no', 'payers', ['collection_id', 'account_no'], unique=False, schema='obligations')
    op.create_index('idx_payers_collection_active', 'payers', ['collection_id', 'is_active'], unique=False, schema='obligations')
    op.create_index('idx_payers_collection_group', 'payers', ['collection_id', 'group_id'], unique=False, schema='obligations')
    op.create_index(op.f('ix_obligations_payers_account_no'), 'payers', ['account_no'], unique=False, schema='obligations')
    op.create_index(op.f('ix_obligations_payers_collection_id'), 'payers', ['collection_id'], unique=False, schema='obligations')
    op.create_index(op.f('ix_obligations_payers_group_id'), 'payers', ['group_id'], unique=False, schema='obligations')
    op.create_index(op.f('ix_obligations_payers_is_active'), 'payers', ['is_active'], unique=False, schema='obligations')
    op.create_index(op.f('ix_obligations_payers_phone'), 'payers', ['phone'], unique=False, schema='obligations')
    op.create_table('tenant_wallets',
    sa.Column('id', app.core.db_types.UUID(), nullable=False),
    sa.Column('collection_id', app.core.db_types.UUID(), nullable=False),
    sa.Column('subscription_id', app.core.db_types.UUID(), nullable=False),
    sa.Column('balance_kes', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('lifetime_topup', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_auto_deduct_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_topup_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['billing.tenant_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id'),
    schema='billing'
    )
    op.create_index('idx_tenant_wallets_collection', 'tenant_wallets', ['collection_id'], unique=False, schema='billing')
    op.create_index(op.f('ix_billing_tenant_wallets_collection_id'), 'tenant_wallets', ['collection_id'], unique=True, schema='billing')
    op.create_table('obligations',
    sa.Column('id', app.core.db_types.UUID(), nullable=False),
    sa.Column('collection_id', app.core.db_types.UUID(), nullable=False),
    sa.Column('payer_id', app.core.db_types.UUID(), nullable=False),
    sa.Column('account_no', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount_due', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PARTIAL', 'SETTLED', 'OVERDUE', 'VOIDED', 'ROLLED', name='obligationstatus'), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', app.core.db_types.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payer_id'], ['obligations.payers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='obligations'
    )
    op.create_index('idx_obligations_collection_account', 'obligations', ['collection_id', 'account_no'], unique=False, schema='obligations')
    op.create_index('idx_obligations_collection_due_date', 'obligations', ['collection_id', 'due_date'], unique=False, schema='obligations')
    op.create_index('idx_obligations_collection_status', 'obligations', ['collection_id', 'status'], unique=False, schema='obligations')
    op.create_index('idx_obligations_created_at_desc', 'obligations', ['created_at'], unique=False, schema='obligations', postgresql_using='btree')
    op.create_index('idx_obligations_payer_status', 'obligations', ['payer_id', 'status'], unique=False, schema='obligations')
    op.create_index(op.f('ix_obligations_obligations_account_no'), 'obligations', ['account_no'], unique=False, schema='obligations')
    op.create_index(op.f('ix_obligations_obligations_collection_id'), 'obligations', ['collection_id'], unique=False, schema='obligations')
    op.create_index(op.f('ix_obligations_obligations_created_by'), 'obligations', ['created_by'], unique=False, schema='obligations')
    op.create_index(op.f('ix_obligations_obligations_is_recurring'), 'obligations', ['is_recurring'], unique=False, schema='obligations')
    op.create_index(op.f('ix_obligations_obligations_payer_id'), 'obligations', ['payer_id'], unique=False, schema='obligations')
    op.create_index(op.f('ix_obligations_obligations_status'), 'obligations', ['status'], unique=False, schema='obligations')
    op.create_table('wallet_transactions',
    sa.Column('id', app.core.db_types.UUID(), nullable=False),
    sa.Column('wallet_id', app.core.db_types.UUID(), nullable=False),
    sa.Column('collection_id', app.core.db_types.UUID(), nullable=False),
    sa.Column('tx_type', sa.Enum('topup', 'deduction', 'reversal', 'subscription', name='wallettxtype'), nullable=False),
    sa.Column('event_type', sa.Enum('reconciliation', 'sms', 'email', 'invoice', 'subscription_fee', 'topup', 'reversal', 'welcome_credit', name='wallettxevent'), nullable=False),
    sa.Column('amount_kes', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['billing.tenant_wallets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='billing'
    )
    op.create_index('idx_wallet_txn_collection_type', 'wallet_transactions', ['collection_id', 'tx_type'], unique=False, schema='billing')
    op.create_index('idx_wallet_txn_reference', 'wallet_transactions', ['reference'], unique=False, schema='billing')
    op.create_index('idx_wallet_txn_wallet_created', 'wallet_transactions', ['wallet_id', 'created_at'], unique=False, schema='billing')
    op.create_index(op.f('ix_billing_wallet_transactions_collection_id'), 'wallet_transactions', ['collection_id'], unique=False, schema='billing')
    op.create_index(op.f('ix_billing_wallet_transactions_event_type'), 'wallet_transactions', ['event_type'], unique=False, schema='billing')
    op.create_index(op.f('ix_billing_wallet_transactions_reference'), 'wallet_transactions', ['reference'], unique=False, schema='billing')
    op.create_index(op.f('ix_billing_wallet_transactions_tx_type'), 'wallet_transactions', ['tx_type'], unique=False, schema='billing')
    op.create_index(op.f('ix_billing_wallet_transactions_wallet_id'), 'wallet_transactions', ['wallet_id'], unique=False, schema='billing')
    op.create_table('transactions',
    sa.Column('id', app.core.db_types.UUID(), nullable=False),
    sa.Column('collection_id', app.core.db_types.UUID(), nullable=False),
    sa.Column('psp_config_id', app.core.db_types.UUID(), nullable=True),
    sa.Column('psp_type', sa.Text(), nullable=False),
    sa.Column('psp_ref', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('account_no', sa.Text(), nullable=True),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('payer_name', sa.Text(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('RAW', 'UNMATCHED', 'MATCHED', 'CATEGORIZED', 'DUPLICATE', 'MANUAL', name='transactionstatus'), nullable=False),
    sa.Column('matched_obligation_id', app.core.db_types.UUID(), nullable=True),
    sa.Column('collection_point_id', app.core.db_types.UUID(), nullable=True),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_point_id'], ['ingestion.collection_points.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matched_obligation_id'], ['obligations.obligations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['psp_config_id'], ['accounts.psp_configs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'psp_ref', name='uq_transaction_collection_psp_ref'),
    schema='ingestion'
    )
    op.create_index('idx_transactions_collection_account', 'transactions', ['collection_id', 'account_no'], unique=False, schema='ingestion')
    op.create_index('idx_transactions_collection_date_amount', 'transactions', ['collection_id', 'ingested_at', 'amount'], unique=False, schema='ingestion')
    op.create_index('idx_transactions_collection_ingested', 'transactions', ['collection_id', 'ingested_at'], unique=False, schema='ingestion')
    op.create_index('idx_transactions_collection_point', 'transactions', ['collection_id', 'collection_point_id'], unique=False, schema='ingestion')
    op.create_index('idx_transactions_collection_status', 'transactions', ['collection_id', 'status'], unique=False, schema='ingestion')
    op.create_index('idx_transactions_psp_type_status', 'transactions', ['psp_type', 'status'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_transactions_account_no'), 'transactions', ['account_no'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_transactions_collection_id'), 'transactions', ['collection_id'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_transactions_collection_point_id'), 'transactions', ['collection_point_id'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_transactions_ingested_at'), 'transactions', ['ingested_at'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_transactions_matched_obligation_id'), 'transactions', ['matched_obligation_id'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_transactions_narration'), 'transactions', ['narration'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_transactions_phone'), 'transactions', ['phone'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_transactions_psp_config_id'), 'transactions', ['psp_config_id'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_transactions_psp_ref'), 'transactions', ['psp_ref'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_transactions_psp_type'), 'transactions', ['psp_type'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_transactions_status'), 'transactions', ['status'], unique=False, schema='ingestion')
    op.create_table('recurring_configs',
    sa.Column('id', app.core.db_types.UUID(), nullable=False),
    sa.Column('obligation_id', app.core.db_types.UUID(), nullable=False),
    sa.Column('recurrence_type', sa.Enum('MONTHLY', 'WEEKLY', 'TERM', 'CUSTOM', name='recurrencetype'), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grace_period_days', sa.Integer(), nullable=False),
    sa.Column('auto_generate', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.obligations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='obligations'
    )
    op.create_index('idx_recurring_next_due', 'recurring_configs', ['next_due_date'], unique=False, schema='obligations')
    op.create_index(op.f('ix_obligations_recurring_configs_next_due_date'), 'recurring_configs', ['next_due_date'], unique=False, schema='obligations')
    op.create_index(op.f('ix_obligations_recurring_configs_obligation_id'), 'recurring_configs', ['obligation_id'], unique=True, schema='obligations')
    op.create_table('transaction_allocations',
    sa.Column('id', app.core.db_types.UUID(), nullable=False),
    sa.Column('transaction_id', app.core.db_types.UUID(), nullable=False),
    sa.Column('obligation_id', app.core.db_types.UUID(), nullable=True),
    sa.Column('payer_id', app.core.db_types.UUID(), nullable=True),
    sa.Column('amount_applied', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_credited', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.obligations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payer_id'], ['obligations.payers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['ingestion.transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ingestion'
    )
    op.create_index(op.f('ix_ingestion_transaction_allocations_obligation_id'), 'transaction_allocations', ['obligation_id'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_transaction_allocations_payer_id'), 'transaction_allocations', ['payer_id'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_transaction_allocations_transaction_id'), 'transaction_allocations', ['transaction_id'], unique=False, schema='ingestion')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingestion_transaction_allocations_transaction_id'), table_name='transaction_allocations', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_transaction_allocations_payer_id'), table_name='transaction_allocations', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_transaction_allocations_obligation_id'), table_name='transaction_allocations', schema='ingestion')
    op.drop_table('transaction_allocations', schema='ingestion')
    op.drop_index(op.f('ix_obligations_recurring_configs_obligation_id'), table_name='recurring_configs', schema='obligations')
    op.drop_index(op.f('ix_obligations_recurring_configs_next_due_date'), table_name='recurring_configs', schema='obligations')
    op.drop_index('idx_recurring_next_due', table_name='recurring_configs', schema='obligations')
    op.drop_table('recurring_configs', schema='obligations')
    op.drop_index(op.f('ix_ingestion_transactions_status'), table_name='transactions', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_transactions_psp_type'), table_name='transactions', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_transactions_psp_ref'), table_name='transactions', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_transactions_psp_config_id'), table_name='transactions', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_transactions_phone'), table_name='transactions', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_transactions_narration'), table_name='transactions', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_transactions_matched_obligation_id'), table_name='transactions', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_transactions_ingested_at'), table_name='transactions', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_transactions_collection_point_id'), table_name='transactions', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_transactions_collection_id'), table_name='transactions', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_transactions_account_no'), table_name='transactions', schema='ingestion')
    op.drop_index('idx_transactions_psp_type_status', table_name='transactions', schema='ingestion')
    op.drop_index('idx_transactions_collection_status', table_name='transactions', schema='ingestion')
    op.drop_index('idx_transactions_collection_point', table_name='transactions', schema='ingestion')
    op.drop_index('idx_transactions_collection_ingested', table_name='transactions', schema='ingestion')
    op.drop_index('idx_transactions_collection_date_amount', table_name='transactions', schema='ingestion')
    op.drop_index('idx_transactions_collection_account', table_name='transactions', schema='ingestion')
    op.drop_table('transactions', schema='ingestion')
    op.drop_index(op.f('ix_billing_wallet_transactions_wallet_id'), table_name='wallet_transactions', schema='billing')
    op.drop_index(op.f('ix_billing_wallet_transactions_tx_type'), table_name='wallet_transactions', schema='billing')
    op.drop_index(op.f('ix_billing_wallet_transactions_reference'), table_name='wallet_transactions', schema='billing')
    op.drop_index(op.f('ix_billing_wallet_transactions_event_type'), table_name='wallet_transactions', schema='billing')
    op.drop_index(op.f('ix_billing_wallet_transactions_collection_id'), table_name='wallet_transactions', schema='billing')
    op.drop_index('idx_wallet_txn_wallet_created', table_name='wallet_transactions', schema='billing')
    op.drop_index('idx_wallet_txn_reference', table_name='wallet_transactions', schema='billing')
    op.drop_index('idx_wallet_txn_collection_type', table_name='wallet_transactions', schema='billing')
    op.drop_table('wallet_transactions', schema='billing')
    op.drop_index(op.f('ix_obligations_obligations_status'), table_name='obligations', schema='obligations')
    op.drop_index(op.f('ix_obligations_obligations_payer_id'), table_name='obligations', schema='obligations')
    op.drop_index(op.f('ix_obligations_obligations_is_recurring'), table_name='obligations', schema='obligations')
    op.drop_index(op.f('ix_obligations_obligations_created_by'), table_name='obligations', schema='obligations')
    op.drop_index(op.f('ix_obligations_obligations_collection_id'), table_name='obligations', schema='obligations')
    op.drop_index(op.f('ix_obligations_obligations_account_no'), table_name='obligations', schema='obligations')
    op.drop_index('idx_obligations_payer_status', table_name='obligations', schema='obligations')
    op.drop_index('idx_obligations_created_at_desc', table_name='obligations', schema='obligations', postgresql_using='btree')
    op.drop_index('idx_obligations_collection_status', table_name='obligations', schema='obligations')
    op.drop_index('idx_obligations_collection_due_date', table_name='obligations', schema='obligations')
    op.drop_index('idx_obligations_collection_account', table_name='obligations', schema='obligations')
    op.drop_table('obligations', schema='obligations')
    op.drop_index(op.f('ix_billing_tenant_wallets_collection_id'), table_name='tenant_wallets', schema='billing')
    op.drop_index('idx_tenant_wallets_collection', table_name='tenant_wallets', schema='billing')
    op.drop_table('tenant_wallets', schema='billing')
    op.drop_index(op.f('ix_obligations_payers_phone'), table_name='payers', schema='obligations')
    op.drop_index(op.f('ix_obligations_payers_is_active'), table_name='payers', schema='obligations')
    op.drop_index(op.f('ix_obligations_payers_group_id'), table_name='payers', schema='obligations')
    op.drop_index(op.f('ix_obligations_payers_collection_id'), table_name='payers', schema='obligations')
    op.drop_index(op.f('ix_obligations_payers_account_no'), table_name='payers', schema='obligations')
    op.drop_index('idx_payers_collection_group', table_name='payers', schema='obligations')
    op.drop_index('idx_payers_collection_active', table_name='payers', schema='obligations')
    op.drop_index('idx_payers_account_no', table_name='payers', schema='obligations')
    op.drop_table('payers', schema='obligations')
    op.drop_index(op.f('ix_ingestion_collection_point_psps_psp_config_id'), table_name='collection_point_psps', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_collection_point_psps_collection_point_id'), table_name='collection_point_psps', schema='ingestion')
    op.drop_table('collection_point_psps', schema='ingestion')
    op.drop_index(op.f('ix_billing_tenant_subscriptions_status'), table_name='tenant_subscriptions', schema='billing')
    op.drop_index(op.f('ix_billing_tenant_subscriptions_plan_id'), table_name='tenant_subscriptions', schema='billing')
    op.drop_index(op.f('ix_billing_tenant_subscriptions_collection_id'), table_name='tenant_subscriptions', schema='billing')
    op.drop_index('idx_tenant_subs_status', table_name='tenant_subscriptions', schema='billing')
    op.drop_index('idx_tenant_subs_collection', table_name='tenant_subscriptions', schema='billing')
    op.drop_table('tenant_subscriptions', schema='billing')
    op.drop_index(op.f('ix_billing_platform_invoices_status'), table_name='platform_invoices', schema='billing')
    op.drop_index(op.f('ix_billing_platform_invoices_invoice_number'), table_name='platform_invoices', schema='billing')
    op.drop_index(op.f('ix_billing_platform_invoices_collection_id'), table_name='platform_invoices', schema='billing')
    op.drop_index('idx_platform_invoices_status', table_name='platform_invoices', schema='billing')
    op.drop_index('idx_platform_invoices_period', table_name='platform_invoices', schema='billing')
    op.drop_index('idx_platform_invoices_collection', table_name='platform_invoices', schema='billing')
    op.drop_table('platform_invoices', schema='billing')
    op.drop_index(op.f('ix_auth_auth_tokens_user_id'), table_name='auth_tokens', schema='auth')
    op.drop_index(op.f('ix_auth_auth_tokens_sent_at'), table_name='auth_tokens', schema='auth')
    op.drop_index(op.f('ix_auth_auth_tokens_hash_tokens'), table_name='auth_tokens', schema='auth')
    op.drop_index('idx_auth_tokens_user_sent_at', table_name='auth_tokens', schema='auth')
    op.drop_index('idx_auth_tokens_hash_lookup', table_name='auth_tokens', schema='auth', postgresql_using='hash')
    op.drop_table('auth_tokens', schema='auth')
    op.drop_index(op.f('ix_obligations_payer_groups_group_type'), table_name='payer_groups', schema='obligations')
    op.drop_index(op.f('ix_obligations_payer_groups_collection_id'), table_name='payer_groups', schema='obligations')
    op.drop_index('idx_payer_groups_collection_type', table_name='payer_groups', schema='obligations')
    op.drop_table('payer_groups', schema='obligations')
    op.drop_index(op.f('ix_obligations_notification_templates_template_type'), table_name='notification_templates', schema='obligations')
    op.drop_index(op.f('ix_obligations_notification_templates_collection_id'), table_name='notification_templates', schema='obligations')
    op.drop_index(op.f('ix_obligations_notification_templates_channel'), table_name='notification_templates', schema='obligations')
    op.drop_index('idx_notif_templates_collection_type', table_name='notification_templates', schema='obligations')
    op.drop_index('idx_notif_templates_collection_channel', table_name='notification_templates', schema='obligations')
    op.drop_table('notification_templates', schema='obligations')
    op.drop_index(op.f('ix_notifications_notification_logs_status'), table_name='notification_logs', schema='notifications')
    op.drop_index(op.f('ix_notifications_notification_logs_payer_id'), table_name='notification_logs', schema='notifications')
    op.drop_index(op.f('ix_notifications_notification_logs_event_type'), table_name='notification_logs', schema='notifications')
    op.drop_index(op.f('ix_notifications_notification_logs_collection_id'), table_name='notification_logs', schema='notifications')
    op.drop_index(op.f('ix_notifications_notification_logs_channel'), table_name='notification_logs', schema='notifications')
    op.drop_index('idx_notif_logs_collection_status', table_name='notification_logs', schema='notifications')
    op.drop_index('idx_notif_logs_collection_event', table_name='notification_logs', schema='notifications')
    op.drop_index('idx_notif_logs_collection_channel', table_name='notification_logs', schema='notifications')
    op.drop_table('notification_logs', schema='notifications')
    op.drop_index(op.f('ix_ingestion_collection_points_cp_type'), table_name='collection_points', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_collection_points_collection_id'), table_name='collection_points', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_collection_points_account_no'), table_name='collection_points', schema='ingestion')
    op.drop_index('idx_cp_collection_type', table_name='collection_points', schema='ingestion')
    op.drop_index('idx_cp_collection_active', table_name='collection_points', schema='ingestion')
    op.drop_table('collection_points', schema='ingestion')
    op.drop_index(op.f('ix_billing_subscription_plans_slug'), table_name='subscription_plans', schema='billing')
    op.drop_table('subscription_plans', schema='billing')
    op.drop_index(op.f('ix_auth_users_verified'), table_name='users', schema='auth')
    op.drop_index(op.f('ix_auth_users_username'), table_name='users', schema='auth')
    op.drop_index(op.f('ix_auth_users_phone'), table_name='users', schema='auth')
    op.drop_index(op.f('ix_auth_users_google_id'), table_name='users', schema='auth')
    op.drop_index(op.f('ix_auth_users_email'), table_name='users', schema='auth')
    op.drop_index(op.f('ix_auth_users_created_at'), table_name='users', schema='auth')
    op.drop_index(op.f('ix_auth_users_auth_type'), table_name='users', schema='auth')
    op.drop_index('idx_users_google_id', table_name='users', schema='auth', postgresql_using='hash')
    op.drop_index('idx_users_email_verified', table_name='users', schema='auth')
    op.drop_index('idx_users_created_at_desc', table_name='users', schema='auth', postgresql_using='btree')
    op.drop_index('idx_users_auth_type_verified', table_name='users', schema='auth')
    op.drop_table('users', schema='auth')
    op.drop_index(op.f('ix_auth_event_log_to_user_id'), table_name='event_log', schema='auth')
    op.drop_index(op.f('ix_auth_event_log_event_name'), table_name='event_log', schema='auth')
    op.drop_index(op.f('ix_auth_event_log_done_by_user_id'), table_name='event_log', schema='auth')
    op.drop_index(op.f('ix_auth_event_log_done_at'), table_name='event_log', schema='auth')
    op.drop_index('idx_event_log_to_user_done_at', table_name='event_log', schema='auth')
    op.drop_index('idx_event_log_event_name_done_at', table_name='event_log', schema='auth')
    op.drop_index('idx_event_log_done_by_user_done_at', table_name='event_log', schema='auth')
    op.drop_index('idx_event_log_done_at_desc', table_name='event_log', schema='auth', postgresql_using='btree')
    op.drop_table('event_log', schema='auth')
    op.drop_index(op.f('ix_accounts_psp_configs_psp_type'), table_name='psp_configs', schema='accounts')
    op.drop_index(op.f('ix_accounts_psp_configs_is_active'), table_name='psp_configs', schema='accounts')
    op.drop_index(op.f('ix_accounts_psp_configs_collection_id'), table_name='psp_configs', schema='accounts')
    op.drop_index('idx_psp_configs_collection_type', table_name='psp_configs', schema='accounts')
    op.drop_index('idx_psp_configs_collection_active', table_name='psp_configs', schema='accounts')
    op.drop_table('psp_configs', schema='accounts')
    op.drop_index(op.f('ix_accounts_business_profiles_collection_id'), table_name='business_profiles', schema='accounts')
    op.drop_table('business_profiles', schema='accounts')
    # ### end Alembic commands ###