"""Add TransactionAllocation

Revision ID: d3e4690c13e8
Revises: f3d04d99e43c
Create Date: 2026-04-12 16:19:22.408337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.core.db_types

# revision identifiers, used by Alembic.
revision: str = 'd3e4690c13e8'
down_revision: Union[str, None] = 'f3d04d99e43c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_allocations',
    sa.Column('id', app.core.db_types.UUID(), nullable=False),
    sa.Column('transaction_id', app.core.db_types.UUID(), nullable=False),
    sa.Column('obligation_id', app.core.db_types.UUID(), nullable=True),
    sa.Column('payer_id', app.core.db_types.UUID(), nullable=True),
    sa.Column('amount_applied', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_credited', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.obligations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payer_id'], ['obligations.payers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['ingestion.transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ingestion'
    )
    op.create_index(op.f('ix_ingestion_transaction_allocations_obligation_id'), 'transaction_allocations', ['obligation_id'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_transaction_allocations_payer_id'), 'transaction_allocations', ['payer_id'], unique=False, schema='ingestion')
    op.create_index(op.f('ix_ingestion_transaction_allocations_transaction_id'), 'transaction_allocations', ['transaction_id'], unique=False, schema='ingestion')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingestion_transaction_allocations_transaction_id'), table_name='transaction_allocations', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_transaction_allocations_payer_id'), table_name='transaction_allocations', schema='ingestion')
    op.drop_index(op.f('ix_ingestion_transaction_allocations_obligation_id'), table_name='transaction_allocations', schema='ingestion')
    op.drop_table('transaction_allocations', schema='ingestion')
    # ### end Alembic commands ###