"""
Notification template renderer.

Replaces {{variable}} placeholders with values from the context dict.
Case-insensitive keys, graceful fallback to empty string for missing vars.

Supported variables:
    payer_name, amount_due, amount_paid, balance, due_date,
    account_no, description, collection_name, currency,
    psp_ref, transaction_date, phone, paybill, shortcode
"""
from datetime import datetime
from typing import Any, Dict, Optional
import re


_PATTERN = re.compile(r"\{\{\s*(\w+)\s*\}\}")


def _format_date(date_str: str) -> str:
    """Try to parse an ISO date string and return a human-readable version."""
    if not date_str:
        return ""
    try:
        dt = datetime.fromisoformat(date_str.replace("Z", "+00:00"))
        return dt.strftime("%d %b %Y, %H:%M")
    except (ValueError, TypeError):
        return date_str


def render(template: str, context: Dict[str, Any]) -> str:

    """
    Render a template string by substituting {{variable}} placeholders.

    >>> render("Hi {{payer_name}}, you owe {{amount_due}}", {"payer_name": "Kamau", "amount_due": "12,000"})
    'Hi Kamau, you owe 12,000'
    """
    normalised = {k.lower(): str(v) if v is not None else "" for k, v in context.items()}

    def replace(match: re.Match) -> str:
        return normalised.get(match.group(1).lower(), "")

    return _PATTERN.sub(replace, template)


def build_context(
    payer_name: str = "",
    amount_due: float = 0,
    amount_paid: float = 0,    # Now refers to TRANSACTION amount (at the moment)
    total_paid: float = 0,     # Now refers to CUMULATIVE amount
    balance: float = 0,
    due_date: str = "",
    account_no: str = "",
    description: str = "",
    collection_name: str = "",
    currency: str = "KES",
    psp_ref: str = "",
    transaction_date: str = "",
    settled_by: str = "",
    phone: str = "",
    **extra,
) -> Dict[str, Any]:
    """
    Build a standard rendering context dict.
    Pass **extra to forward any tenant-specific meta fields.
    """
    # Format basic amounts
    f_amount_paid = f"{amount_paid:,.2f}"
    f_total_paid = f"{total_paid:,.2f}"
    f_balance = f"{balance:,.2f}"
    f_date = _format_date(transaction_date)

    ctx = {
        "payer_name":       payer_name,
        "amount_due":       f"{amount_due:,.2f}",
        "amount_paid":      f_amount_paid,
        "total_paid":       f_total_paid,
        "balance":          f_balance,
        "due_date":         _format_date(due_date),
        "account_no":       account_no,
        "description":      description,
        "collection_name":  collection_name,
        "currency":         currency,
        "psp_ref":          psp_ref,
        "transaction_date": f_date,
        "settled_by":       settled_by,
        "phone":            phone,
    }

    # Generate Digital Receipt Block
    # Text-only (for SMS / Simple Email)
    receipt_txt = (
        f"--- RECEIPT ---\n"
        f"Amount: {currency} {f_amount_paid}\n"
        f"Account Ref: {account_no}\n"
        f"Ref: {psp_ref}\n"
        f"Date: {f_date}\n"
        f"-----------------------"
    )

    # HTML Styled (for wrapping in wrap_in_template)
    receipt_html = f"""
    <div style="background: #f9fafb; border: 1px dashed #d1d5db; border-radius: 12px; padding: 16px; font-family: monospace; margin: 16px 0;">
        <div style="text-align: center; border-bottom: 1px dashed #d1d5db; padding-bottom: 8px; margin-bottom: 8px; font-weight: bold;">RECEIPT</div>
        <div style="display: flex; justify-content: space-between; margin: 4px 0;"><span>Amount:</span> <b>{currency} {f_amount_paid}</b></div>
        <div style="display: flex; justify-content: space-between; margin: 4px 0;"><span>Account:</span> <b>{account_no}</b></div>
        <div style="display: flex; justify-content: space-between; margin: 4px 0;"><span>Reference:</span> <b>{psp_ref}</b></div>
        <div style="display: flex; justify-content: space-between; margin: 4px 0;"><span>Date:</span> <b>{f_date}</b></div>
        <div style="text-align: center; border-top: 1px dashed #d1d5db; padding-top: 8px; margin-top: 8px; font-size: 10px; color: #6b7280;">Generated by PesaGrid</div>
    </div>
    """

    ctx["digital_receipt"] = receipt_txt
    ctx["digital_receipt_html"] = receipt_html

    ctx.update(extra)
    return ctx
def wrap_in_template(content_html: str, business_name: Optional[str] = None) -> str:
    """
    Wrap the generated content in a modern, responsive HTML email template.
    Matches the clean, vibrant landing page aesthetic.
    """
    # Primary accent color from the landing page: #adff2f (GreenYellow)
    accent_color = "#adff2f"
    platform_name = "PesaGrid"

    # Determine attribution text for the footer
    attribution = ""
    if business_name and business_name != platform_name:
        attribution = f"<p>This notification was sent by {platform_name} on behalf of <b>{business_name}</b>.</p>"
    
    return f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        body {{ 
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; 
            background-color: #f3f4f6; 
            margin: 0; 
            padding: 20px; 
            color: #111827; 
            -webkit-font-smoothing: antialiased;
        }}
        .wrapper {{
            max-width: 600px;
            margin: 0 auto;
        }}
        .container {{ 
            background: #ffffff; 
            border-radius: 24px; 
            box-shadow: 0 10px 15px -3px rgba(0,0,0,0.1); 
            overflow: hidden; 
            border: 1px solid #e5e7eb; 
        }}
        .header {{ 
            background: {accent_color}; 
            padding: 40px 30px; 
            text-align: center; 
        }}
        .header h1 {{ 
            margin: 0; 
            font-size: 28px; 
            font-weight: 900; 
            letter-spacing: -0.05em; 
            color: #111827;
        }}
        .content {{ 
            padding: 40px 30px; 
            line-height: 1.6; 
            font-size: 16px;
        }}
        .content h2 {{
            margin-top: 0;
            font-size: 20px;
            font-weight: 700;
            color: #111827;
            letter-spacing: -0.02em;
        }}
        .content p {{
            margin: 16px 0;
            color: #4b5563;
        }}
        .footer {{ 
            padding: 30px; 
            text-align: center; 
            font-size: 13px; 
            color: #9ca3af; 
        }}
        .footer b {{
            color: #6b7280;
        }}
        .footer a {{
            color: #6b7280;
            text-decoration: underline;
        }}
        .details-box {{
            background: #f9fafb;
            border-radius: 16px;
            padding: 20px;
            margin: 24px 0;
            border: 1px solid #f3f4f6;
        }}
        .button {{
            display: inline-block;
            background: {accent_color};
            color: #111827;
            padding: 14px 28px;
            border-radius: 14px;
            font-weight: 700;
            text-decoration: none;
            margin-top: 10px;
            box-shadow: 0 4px 6px -1px rgba(0,0,0,0.05);
        }}
        .button-black {{
            display: inline-block;
            background: #111827;
            color: #ffffff !important;
            padding: 14px 28px;
            border-radius: 14px;
            font-weight: 700;
            text-decoration: none;
            margin-top: 10px;
            box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1);
        }}
    </style>
</head>
<body>
    <div class="wrapper">
        <div class="container">
            <div class="header">
                <h1>{platform_name}</h1>
            </div>
            <div class="content">
                {content_html}
            </div>
        </div>
        <div class="footer">
            {attribution}
            &copy; {datetime.now().year} {platform_name}. All rights reserved.<br>
            Automated collections & reconciliation made simple.
        </div>
    </div>
</body>
</html>
"""
